remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [QuantumSpinozist]
description: [I am interested in Machine Learning, Programming, Matheamtics and sometimes Physics (I might also write about other things occasionaly).]
