remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown 

title: [QuantumSpinozist]
description: ['I like Machines that learn, Programming languages that are (not actually) named after snakes, Hilbert spaces that are separable and all things Markovian. I might write about these things sometimes but also others.']

# Enable MathJax for LaTeX
katex: false  # Make sure KaTeX is not used if MathJax is preferred
mathjax: true  # Enable MathJax

# Optionally, you can add additional configuration
mathjax_config:
  version: "2.7.7"  # Specify the MathJax version (or remove to use the latest)

