remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [QuantumSpinozist]
description: ['I am interested in Machine Learning, Programming, Mathematics and sometimes Physics (I might also write about other things occasionally).']

# Enable MathJax for LaTeX
katex: false  # Make sure KaTeX is not used if MathJax is preferred
mathjax: true  # Enable MathJax

# Optionally, you can add additional configuration
mathjax_config:
  version: "2.7.7"  # Specify the MathJax version (or remove to use the latest)

